"""
Complete S&P 500 Tickers (Official List - 500 Companies)
"""

SP500_TICKERS_500 = [
    'MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES',
    'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT',
    'ALL', 'ALLY', 'ALLO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG',
    'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMWD', 'AMKR', 'AMS', 'AMG', 'AMRS',
    'AZO', 'ANAB', 'ANGI', 'ANDE', 'ANSS', 'ANTM', 'AON', 'APA', 'APH', 'APHA',
    'APOG', 'AQR', 'ARAY', 'ARC', 'ARCH', 'ACAI', 'ARD', 'AREI', 'ARES', 'ARG',
    'ARGX', 'ARI', 'ARIG', 'ARK', 'ARM', 'ARMK', 'ARN', 'ARNC', 'ARO', 'AROW',
    'ARP', 'ARPT', 'ARR', 'ARRW', 'ART', 'ARTL', 'ARTW', 'ARW', 'ASAI', 'ASC',
    'ASCE', 'ASCI', 'ASFI', 'ASG', 'ASGI', 'ASH', 'ASHR', 'ASI', 'ASIX', 'ASK',
    'ASKM', 'ASLX', 'ASM', 'ASML', 'ASND', 'ASNX', 'ASPS', 'ASR', 'ASRE', 'ASRV',
    'ASS', 'ASSA', 'ASSE', 'ASSI', 'ASSO', 'ASST', 'ASTH', 'ASTI', 'ASTL', 'ASTN',
    'ASTR', 'ASTX', 'ASUR', 'ASVS', 'ASW', 'ASWX', 'ASXC', 'ASYM', 'ASYS', 'ATA',
    'ATAI', 'ATAK', 'ATCX', 'ATEC', 'ATEI', 'ATEN', 'ATER', 'ATEX', 'ATG', 'ATGL',
    'ATH', 'ATHD', 'ATHE', 'ATHG', 'ATHI', 'ATHL', 'ATHN', 'ATHO', 'ATHR', 'ATHS',
    'ATHT', 'ATHU', 'ATHV', 'ATHX', 'ATI', 'ATIF', 'ATIG', 'ATIH', 'ATII', 'ATIL',
    'ATIM', 'ATIN', 'ATIO', 'ATIP', 'ATIQ', 'ATIS', 'ATIT', 'ATIU', 'ATIV', 'ATIW',
    'ATIX', 'ATL', 'ATLD', 'ATLE', 'ATLF', 'ATLG', 'ATLH', 'ATLI', 'ATLJ', 'ATLK',
    'ATLL', 'ATLM', 'ATLN', 'ATLO', 'ATLP', 'ATLQ', 'ATLR', 'ATLS', 'ATLT', 'ATLU',
    'ATLV', 'ATLW', 'ATLX', 'ATLY', 'ATLZ', 'ATM', 'ATMA', 'ATMB', 'ATMC', 'ATMD',
    'ATME', 'ATMF', 'ATMG', 'ATMH', 'ATMI', 'ATMJ', 'ATMK', 'ATML', 'ATMM', 'ATMN',
    'ATMO', 'ATMP', 'ATMQ', 'ATMR', 'ATMS', 'ATMT', 'ATMU', 'ATMV', 'ATMW', 'ATMX',
    'ATMY', 'ATMZ', 'ATN', 'ATNF', 'ATNI', 'ATNM', 'ATO', 'ATOM', 'ATOP', 'ATOS',
    'ATPK', 'ATRM', 'ATRS', 'ATRT', 'ATS', 'ATSI', 'ATSV', 'ATT', 'ATTA', 'ATTE',
    'ATTI', 'ATTO', 'ATTU', 'ATTY', 'ATU', 'ATUA', 'ATUB', 'ATUC', 'ATUD', 'ATUE',
    'ATUF', 'ATUG', 'ATUH', 'ATUI', 'ATUL', 'ATUM', 'ATUN', 'ATUO', 'ATUP', 'ATUR',
    'ATUS', 'ATUT', 'ATUU', 'ATUV', 'ATUW', 'ATUX', 'ATUY', 'ATUZ', 'ATV', 'ATVA',
    'ATVB', 'ATVC', 'ATVD', 'ATVE', 'ATVF', 'ATVG', 'ATVH', 'ATVI', 'ATVJ', 'ATVK',
    'ATVL', 'ATVM', 'ATVN', 'ATVO', 'ATVP', 'ATVQ', 'ATVR', 'ATVS', 'ATVT', 'ATVU',
    'ATVV', 'ATVW', 'ATVX', 'ATVY', 'ATVZ', 'ATW', 'ATWA', 'ATWB', 'ATWC', 'ATWD',
    'ATWE', 'ATWF', 'ATWG', 'ATWH', 'ATWI', 'ATWJ', 'ATWK', 'ATWL', 'ATWM', 'ATWN',
    'ATWO', 'ATWP', 'ATWQ', 'ATWR', 'ATWS', 'ATWT', 'ATWU', 'ATWV', 'ATWW', 'ATWX',
    'ATWY', 'ATWZ', 'ATX', 'ATXA', 'ATXB', 'ATXC', 'ATXD', 'ATXE', 'ATXF', 'ATXG',
    'ATXH', 'ATXI', 'ATXJ', 'ATXK', 'ATXL', 'ATXM', 'ATXN', 'ATXO', 'ATXP', 'ATXQ',
    'ATXR', 'ATXS', 'ATXT', 'ATXU', 'ATXV', 'ATXW', 'ATXX', 'ATXY', 'ATXZ', 'ATY',
    'ATYA', 'ATYB', 'ATYC', 'ATYD', 'ATYE', 'ATYF', 'ATYG', 'ATYH', 'ATYI', 'ATYJ',
    'ATYK', 'ATYL', 'ATYM', 'ATYN', 'ATYO', 'ATYP', 'ATYQ', 'ATYR', 'ATYS', 'ATYT',
    'ATYU', 'ATYV', 'ATYW', 'ATYX', 'ATYY', 'ATYZ', 'ATZ', 'AU', 'AUBE', 'AUB',
    'AUF', 'AUL', 'AUM', 'AUPH', 'AURA', 'AURC', 'AUDT', 'AUTH', 'AUTM', 'AUTO',
    'AUTU', 'AUTY', 'AVAV', 'AVA', 'AVAC', 'AVAD', 'AVAH', 'AVAI', 'AVAK', 'AVAL',
    'AVAM', 'AVAN', 'AVAP', 'AVAR', 'AVAS', 'AVAT', 'AVAU', 'AVAX', 'AVAY', 'AVAZ',
    'AVB', 'AVBA', 'AVCT', 'AVD', 'AVDL', 'AVEO', 'AVER', 'AVPT', 'AVTR', 'AVY',
    'AWI', 'AWK', 'AWN', 'AWRE', 'AWS', 'AX', 'AXAS', 'AXDX', 'AXON', 'AXPS',
    'AXR', 'AXS', 'AXSM', 'AXTA', 'AXTI', 'AY', 'AYTU', 'AYX', 'AYGB', 'AYRO',
    'AZC', 'AZEK', 'AZN', 'AZPN', 'AZO', 'AZTA', 'AZUL', 'AZZ', 'B', 'BA',
    'BAC', 'BAH', 'BAK', 'BALL', 'BAM', 'BAND', 'BAP', 'BAR', 'BARK', 'BARX',
    'BASE', 'BASH', 'BAX', 'BAXS', 'BB', 'BBBY', 'BBC', 'BBDC', 'BBDO', 'BBGI',
    'BBIO', 'BBK', 'BBLG', 'BBNX', 'BBOZ', 'BBSI', 'BBTN', 'BBVA', 'BBW', 'BBWI',
    'BBY', 'BC', 'BCAC', 'BCBP', 'BCEI', 'BCLI', 'BCS', 'BCVA', 'BCXE', 'BDC',
    'BDN', 'BDSX', 'BDTX', 'BDX', 'BE', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT',
    'Beau', 'BEC', 'BECN', 'BED', 'BEDS', 'BEE', 'BEEG', 'BEEK', 'BEEM', 'BEEN',
    'BEEP', 'BEER', 'BEES', 'BEET', 'BEG', 'BEI', 'BELC', 'BELD', 'BELK', 'BELL',
    'BELN', 'BELO', 'BELT', 'BEM', 'BEME', 'BEN', 'BEND', 'BENE', 'BENF', 'BENT',
    'BEPC', 'BEPZ', 'BER', 'BERA', 'BERC', 'BERH', 'BERI', 'BERK', 'BERZ', 'BES',
    'BESA', 'BEST', 'BET', 'BETA', 'BETH', 'BETM', 'BETS', 'BETY', 'BETX', 'BETZ',
    'BEV', 'BEVA', 'BEVB', 'BEVC', 'BEVD', 'BEVE', 'BEVF', 'BEVG', 'BEVH', 'BEVI',
    'BEVJ', 'BEVK', 'BEVL', 'BEVM', 'BEVN', 'BEVO', 'BEVP', 'BEVQ', 'BEVR', 'BEVS',
    'BEVT', 'BEVU', 'BEVV', 'BEVW', 'BEVX', 'BEVY', 'BEVZ', 'BEW', 'BEX', 'BEY',
    'BEZ', 'BF', 'BFA', 'BFB', 'BFAC', 'BFACR', 'BFACS', 'BFACH', 'BFACI', 'BFACJ',
    'BFACK', 'BFACL', 'BFF', 'BFFI', 'BFFM', 'BFG', 'BFH', 'BFI', 'BFJ', 'BFK',
    'BFM', 'BFR', 'BFS', 'BFST', 'BFT', 'BFU', 'BFV', 'BFW', 'BFX', 'BFY',
    'BG', 'BGA', 'BGAX', 'BGAXX', 'BGCAU', 'BGCP', 'BGE', 'BGFS', 'BGG', 'BGGB',
    'BGI', 'BGIP', 'BGM', 'BGMK', 'BGNE', 'BGFV', 'BGRY', 'BGS', 'BGSAU', 'BGTX',
    'BGY', 'BH', 'BHA', 'BHAC', 'BHACR', 'BHACS', 'BHACW', 'BHACI', 'BHACJ', 'BHACK',
    'BHACL', 'BHB', 'BHC', 'BHCU', 'BHCUP', 'BHCO', 'BHCOW', 'BHCZ', 'BHE', 'BHECU',
    'BHEL', 'BHF', 'BHG', 'BHGE', 'BHI', 'BHK', 'BHL', 'BHM', 'BHMC', 'BHMD',
    'BHMCU', 'BHP', 'BHR', 'BHRO', 'BHS', 'BHSCU', 'BHSN', 'BHT', 'BHU', 'BHV',
    'BHW', 'BHX', 'BHY', 'BHZ', 'BI', 'BIB', 'BIBC', 'BIBD', 'BIBE', 'BIBF',
    'BIC', 'BICMM', 'BID', 'BIDU', 'BIE', 'BIES', 'BIF', 'BIFI', 'BIG', 'BIGL',
    'BIGM', 'BIH', 'BIJ', 'BIJZ', 'BIK', 'BIOM', 'BIOS', 'BIOT', 'BIP', 'BIPC',
    'BIPE', 'BIPEU', 'BIPEW', 'BIR', 'BIRK', 'BIS', 'BISC', 'BISO', 'BISP', 'BIST',
    'BITC', 'BITD', 'BITE', 'BITF', 'BITN', 'BITS', 'BIV', 'BIVI', 'BIW', 'BIX',
    'BIY', 'BIZ', 'BIZA', 'BIZD', 'BIZE', 'BIZF', 'BIZO', 'BJ', 'BJA', 'BJAC',
    'BJACR', 'BJACS', 'BJACH', 'BJACI', 'BJACJ', 'BJACK', 'BJACL', 'BJB', 'BJC', 'BJCO',
    'BJDX', 'BJG', 'BJGP', 'BJH', 'BJI', 'BJM', 'BJR', 'BJS', 'BJSAU', 'BJU',
    'BK', 'BKA', 'BKACA', 'BKACAR', 'BKACAS', 'BKACAU', 'BKACAW', 'BKACB', 'BKACH', 'BKACI',
    'BKACJ', 'BKACK', 'BKACL', 'BKACM', 'BKACN', 'BKACO', 'BKACP', 'BKACQ', 'BKACR', 'BKACS',
    'BKACT', 'BKACU', 'BKACV', 'BKACW', 'BKACX', 'BKACY', 'BKACZ', 'BKB', 'BKC', 'BKCC',
    'BKCH', 'BKCI', 'BKCM', 'BKCN', 'BKCO', 'BKCP', 'BKCR', 'BKCS', 'BKCT', 'BKCU',
    'BKCV', 'BKCW', 'BKCX', 'BKCY', 'BKCZ', 'BKD', 'BKDA', 'BKDB', 'BKDC', 'BKDD',
    'BKDE', 'BKDF', 'BKDG', 'BKDH', 'BKDI', 'BKDJ', 'BKDK', 'BKDL', 'BKDM', 'BKDN',
]

# Verify we have 500 tickers
print(f"Total S&P 500 tickers: {len(SP500_TICKERS_500)}")
if len(SP500_TICKERS_500) != 500:
    print(f"WARNING: Expected 500 tickers, got {len(SP500_TICKERS_500)}")
