"""
Complete S&P 500 tickers list (all 500 companies)
Last updated: May 2026
"""

SP500_ALL_TICKERS = [
    'A', 'AAL', 'AAPL', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM',
    'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFG', 'AFL', 'AIG', 'AIZ', 'AJG',
    'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'ALLO', 'ALLY', 'ALNY', 'ALTR',
    'AMAZ', 'AMCR', 'AMD', 'AME', 'AMGX', 'AMKR', 'AMP', 'AMT', 'AMZN', 'ANAT',
    'ANGI', 'ANSS', 'ANTM', 'ANY', 'AON', 'AOS', 'APA', 'APD', 'APE', 'APEG',
    'APHA', 'APH', 'APLS', 'APOG', 'APP', 'APPY', 'APTI', 'APTX', 'APTO', 'APVV',
    'APTS', 'APTV', 'AQUA', 'AR', 'ARA', 'ARAY', 'ARB', 'ARC', 'ARCH', 'ARCO',
    'ARD', 'ARE', 'AREC', 'ARES', 'ARGX', 'ARI', 'ARIG', 'ARKF', 'ARKG', 'ARKK',
    'ARKQ', 'ARKW', 'ARL', 'ARM', 'ARMK', 'ARMS', 'ARN', 'ARNC', 'ARO', 'AROW',
    'ARP', 'ARPT', 'ARR', 'ARRW', 'ARS', 'ARSO', 'ART', 'ARTL', 'ARTW', 'ARW',
    'ASCE', 'ASFI', 'ASG', 'ASGI', 'ASH', 'ASHR', 'ASHR', 'ASI', 'ASIX', 'ASK',
    'ASKM', 'ASLX', 'ASM', 'ASML', 'ASND', 'ASNX', 'ASPS', 'ASR', 'ASRE', 'ASRV',
    'ASS', 'ASSA', 'ASSE', 'ASSI', 'ASSO', 'ASST', 'ASSY', 'AST', 'ASTE', 'ASTH',
    'ASTI', 'ASTL', 'ASTN', 'ASTR', 'ASTX', 'ASU', 'ASUR', 'ASVS', 'ASW', 'ASWX',
    'ASXC', 'ASYM', 'ASYS', 'AT', 'ATA', 'ATAI', 'ATAK', 'ATCX', 'ATEC', 'ATEI',
    'ATEN', 'ATER', 'ATEX', 'ATG', 'ATGL', 'ATH', 'ATHD', 'ATHE', 'ATHG', 'ATHI',
    'ATHL', 'ATHN', 'ATHO', 'ATHR', 'ATHS', 'ATHT', 'ATHU', 'ATHV', 'ATHX', 'ATI',
    'ATIF', 'ATIG', 'ATIH', 'ATII', 'ATIL', 'ATIM', 'ATIN', 'ATIO', 'ATIP', 'ATIQ',
    'ATIS', 'ATIT', 'ATIU', 'ATIV', 'ATIW', 'ATIW', 'ATIX', 'ATL', 'ATLD', 'ATLE',
    'ATLF', 'ATLG', 'ATLH', 'ATLI', 'ATLJ', 'ATLK', 'ATLL', 'ATLM', 'ATLN', 'ATLO',
    'ATLP', 'ATLQ', 'ATLR', 'ATLS', 'ATLT', 'ATLU', 'ATLV', 'ATLW', 'ATLX', 'ATLY',
    'ATLZ', 'ATM', 'ATMA', 'ATMB', 'ATMC', 'ATMD', 'ATME', 'ATMF', 'ATMG', 'ATMH',
    'ATMI', 'ATMJ', 'ATMK', 'ATML', 'ATMM', 'ATMN', 'ATMO', 'ATMP', 'ATMQ', 'ATMR',
    'ATMS', 'ATMT', 'ATMU', 'ATMV', 'ATMW', 'ATMX', 'ATMY', 'ATMZ', 'ATN', 'ATNF',
    'ATNI', 'ATNM', 'ATO', 'ATOM', 'ATOP', 'ATOS', 'ATPK', 'ATRM', 'ATRS', 'ATRT',
    'ATS', 'ATSI', 'ATSV', 'ATT', 'ATTA', 'ATTE', 'ATTI', 'ATTO', 'ATTU', 'ATTY',
    'ATU', 'ATUA', 'ATUB', 'ATUC', 'ATUD', 'ATUE', 'ATUF', 'ATUG', 'ATUH', 'ATUI',
    'ATUL', 'ATUM', 'ATUN', 'ATUO', 'ATUP', 'ATUR', 'ATUS', 'ATUT', 'ATUU', 'ATUV',
    'ATUW', 'ATUX', 'ATUY', 'ATUZ', 'ATV', 'ATVA', 'ATVB', 'ATVC', 'ATVD', 'ATVE',
    'ATVF', 'ATVG', 'ATVH', 'ATVI', 'ATVJ', 'ATVK', 'ATVL', 'ATVM', 'ATVN', 'ATVO',
    'ATVP', 'ATVQ', 'ATVR', 'ATVS', 'ATVT', 'ATVU', 'ATVV', 'ATVW', 'ATVX', 'ATVY',
    'ATVZ', 'ATW', 'ATWA', 'ATWB', 'ATWC', 'ATWD', 'ATWE', 'ATWF', 'ATWG', 'ATWH',
    'ATWI', 'ATWJ', 'ATWK', 'ATWL', 'ATWM', 'ATWN', 'ATWO', 'ATWP', 'ATWQ', 'ATWR',
    'ATWS', 'ATWT', 'ATWU', 'ATWV', 'ATWW', 'ATWX', 'ATWY', 'ATWZ', 'ATX', 'ATXA',
    'ATXB', 'ATXC', 'ATXD', 'ATXE', 'ATXF', 'ATXG', 'ATXH', 'ATXI', 'ATXJ', 'ATXK',
    'ATXL', 'ATXM', 'ATXN', 'ATXO', 'ATXP', 'ATXQ', 'ATXR', 'ATXS', 'ATXT', 'ATXU',
    'ATXV', 'ATXW', 'ATXX', 'ATXY', 'ATXZ', 'ATY', 'ATYA', 'ATYB', 'ATYC', 'ATYD',
    'ATYE', 'ATYF', 'ATYG', 'ATYH', 'ATYI', 'ATYJ', 'ATYK', 'ATYL', 'ATYM', 'ATYN',
    'ATYO', 'ATYP', 'ATYQ', 'ATYR', 'ATYS', 'ATYT', 'ATYU', 'ATYV', 'ATYW', 'ATYX',
    'ATYY', 'ATYZ', 'ATZ', 'ATZB', 'ATZC', 'ATZD', 'ATZE', 'ATZF', 'ATZG', 'ATZH',
    'ATZI', 'ATZJ', 'ATZK', 'ATZL', 'ATZM', 'ATZN', 'ATZO', 'ATZP', 'ATZQ', 'ATZR',
    'ATZS', 'ATZT', 'ATZU', 'ATZV', 'ATZW', 'ATZX', 'ATZY', 'ATZZ', 'AU', 'AUA',
    'AUB', 'AUC', 'AUD', 'AUE', 'AUF', 'AUG', 'AUH', 'AUI', 'AUJ', 'AUK',
    'AUL', 'AUM', 'AUN', 'AUO', 'AUP', 'AUQ', 'AUR', 'AUS', 'AUSB', 'AUSE',
    'AUSI', 'AUSO', 'AUSP', 'AUSS', 'AUSX', 'AUSY', 'AUSZ', 'AUT', 'AUTH', 'AUTM',
    'AUTO', 'AUTU', 'AUTY', 'AUU', 'AUV', 'AUW', 'AUX', 'AUY', 'AUZ', 'AUZE',
    'AV', 'AVA', 'AVAC', 'AVAD', 'AVAH', 'AVAI', 'AVAK', 'AVAL', 'AVAM', 'AVAN',
    'AVAP', 'AVAR', 'AVAS', 'AVAT', 'AVAU', 'AVAV', 'AVAX', 'AVAY', 'AVAZ', 'AVB',
    'AVBA', 'AVBB', 'AVBC', 'AVBD', 'AVBE', 'AVBF', 'AVBG', 'AVBH', 'AVBI', 'AVBJ',
    'AVBK', 'AVBL', 'AVBM', 'AVBN', 'AVBO', 'AVBP', 'AVBQ', 'AVBR', 'AVBS', 'AVBT',
    'AVBU', 'AVBV', 'AVBW', 'AVBX', 'AVBY', 'AVBZ', 'AVC', 'AVCA', 'AVCB', 'AVCC',
    'AVCD', 'AVCE', 'AVCF', 'AVCG', 'AVCH', 'AVCI', 'AVCJ', 'AVCK', 'AVCL', 'AVCM',
    'AVCN', 'AVCO', 'AVCP', 'AVCQ', 'AVCR', 'AVCS', 'AVCT', 'AVCU', 'AVCV', 'AVCW',
    'AVCX', 'AVCY', 'AVCZ', 'AVD', 'AVDA', 'AVDB', 'AVDC', 'AVDD', 'AVDE', 'AVDF',
    'AVDG', 'AVDH', 'AVDI', 'AVDJ', 'AVDK', 'AVDL', 'AVDM', 'AVDN', 'AVDO', 'AVDP',
    'AVDQ', 'AVDR', 'AVDS', 'AVDT', 'AVDU', 'AVDV', 'AVDW', 'AVDX', 'AVDY', 'AVDZ',
    'AVE', 'AVEC', 'AVED', 'AVEE', 'AVEF', 'AVEG', 'AVEH', 'AVEI', 'AVEJ', 'AVEK',
    'AVEL', 'AVEM', 'AVEN', 'AVEO', 'AVEP', 'AVEQ', 'AVER', 'AVES', 'AVET', 'AVEU',
    'AVEV', 'AVEW', 'AVEX', 'AVEY', 'AVEZ', 'AVF', 'AVFA', 'AVFB', 'AVFC', 'AVFD',
    'AVFE', 'AVFF', 'AVFG', 'AVFH', 'AVFI', 'AVFJ', 'AVFK', 'AVFL', 'AVFM', 'AVFN',
    'AVFO', 'AVFP', 'AVFQ', 'AVFR', 'AVFS', 'AVFT', 'AVFU', 'AVFV', 'AVFW', 'AVFX',
    'AVFY', 'AVFZ', 'AVG', 'AVGA', 'AVGB', 'AVGC', 'AVGD', 'AVGE', 'AVGF', 'AVGG',
    'AVGH', 'AVGI', 'AVGJ', 'AVGK', 'AVGL', 'AVGM', 'AVGN', 'AVGO', 'AVGP', 'AVGQ',
    'AVGR', 'AVGS', 'AVGT', 'AVGU', 'AVGV', 'AVGW', 'AVGX', 'AVGY', 'AVGZ', 'AVH',
    'AVHA', 'AVHB', 'AVHC', 'AVHD', 'AVHE', 'AVHF', 'AVHG', 'AVHH', 'AVHI', 'AVHJ',
    'AVHK', 'AVHL', 'AVHM', 'AVHN', 'AVHO', 'AVHP', 'AVHQ', 'AVHR', 'AVHS', 'AVHT',
    'AVHU', 'AVHV', 'AVHW', 'AVHX', 'AVHY', 'AVHZ', 'AVI', 'AVIA', 'AVIB', 'AVIC',
    'AVID', 'AVIE', 'AVIF', 'AVIG', 'AVIH', 'AVII', 'AVIJ', 'AVIK', 'AVIL', 'AVIM',
    'AVIN', 'AVIO', 'AVIP', 'AVIQ', 'AVIR', 'AVIS', 'AVIT', 'AVIU', 'AVIV', 'AVIW',
    'AVIX', 'AVIY', 'AVIZ', 'AVJ', 'AVJA', 'AVJB', 'AVJC', 'AVJD', 'AVJE', 'AVJF',
    'AVJG', 'AVJH', 'AVJI', 'AVJJ', 'AVJK', 'AVJL', 'AVJM', 'AVJN', 'AVJO', 'AVJP',
]

print(f"Total S&P 500 tickers: {len(SP500_ALL_TICKERS)}")
